services:
  app:
    image: tolak/figma-context-mcp:v0.1.1
    # ports: # Using caddy to proxy the server to enhance security, so no need to expose the port
    #   - "3333:3333"
    environment:
      - NODE_ENV=production
      # You'll need to provide your Figma API key through environment variables
      - FIGMA_API_KEY=${FIGMA_API_KEY}
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: unless-stopped
    networks:
      - internal

  proxy:
    image: caddy:2.8
    ports:
      - "18080:80"
    environment:
      - BEARER_TOKEN=${BEARER_TOKEN}
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - internal

configs:
  caddy_config:
    content: |
      :80 {
          @valid_auth {
              header Authorization "Bearer $BEARER_TOKEN"
          }
          route @valid_auth {
              reverse_proxy app:3333
          }
          route {
              respond 401 {
                  body "Unauthorized"
                  close
              }
          }
      }

networks:
  internal:
    driver: bridge
