services:
  app:
    image: mooflowai/moof-mcp:p4aacnr9zhke@sha256:a11b0cf0643c9d6cb0e299b287f7be36302adb1bafd86107fb46ee5859d784b6
    ports:
      - "5555:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      MOOF_API_KEY: ${MOOF_API_KEY:?MOOF_API_KEY is required}
      MCP_API_KEY: ${MCP_API_KEY:?MCP_API_KEY is required}
      BASE_URL: ${BASE_URL:-https://app.moof.fun}
      MCP_BASE_URL: ${MCP_BASE_URL:-https://dev-mcp-api.mooflow.ai}
    restart: unless-stopped
