services:
  app:
    image: tolak/evm-mcp-server:v0.1.0
    # ports: # Using caddy to proxy the server to enhance security, so no need to expose the port
    #   - "3000:3000"
    environment:
      - PORT=3000
      - EVM_PRIVATE_KEY=${EVM_PRIVATE_KEY}
      - RPC_URL=${RPC_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - COINGECKO_PRO_API_KEY=${COINGECKO_PRO_API_KEY}
    restart: unless-stopped
    networks:
      - internal

  proxy:
    image: caddy:2.8
    ports:
      - "18080:80"
    environment:
      - BEARER_TOKEN=${BEARER_TOKEN}
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - internal

configs:
  caddy_config:
    content: |
      :80 {
          @valid_auth {
              header Authorization "Bearer $BEARER_TOKEN"
          }
          route @valid_auth {
              reverse_proxy app:3000
          }
          route {
              respond 401 {
                  body "Unauthorized"
                  close
              }
          }
      }

networks:
  internal:
    driver: bridge
