#!/usr/bin/env bun
/**
 * Generate src/commands/help/topics.generated.ts from docs/help/topics/*.md.
 *
 * Each .md file becomes one help topic. The topic name is the file basename
 * (without extension). The description is the first non-empty, non-heading
 * line of the file.
 *
 * Run: bun run gen:help
 */
import { spawnSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");
const TOPICS_DIR = join(ROOT, "docs", "help", "topics");
const OUT_FILE = join(ROOT, "src", "commands", "help", "topics.generated.ts");

interface Topic {
	name: string;
	description: string;
	content: string;
}

function extractDescription(content: string): string {
	for (const rawLine of content.split("\n")) {
		const line = rawLine.trim();
		if (line === "") continue;
		if (line.startsWith("#")) continue;
		return line;
	}
	return "";
}

function collectTopics(): Topic[] {
	const entries = readdirSync(TOPICS_DIR, { withFileTypes: true });
	const topics: Topic[] = [];
	for (const entry of entries) {
		if (!entry.isFile()) continue;
		if (!entry.name.endsWith(".md")) continue;
		const name = entry.name.replace(/\.md$/, "");
		const content = readFileSync(join(TOPICS_DIR, entry.name), "utf-8");
		topics.push({
			name,
			description: extractDescription(content),
			content,
		});
	}
	topics.sort((a, b) => a.name.localeCompare(b.name));
	return topics;
}

function serializeString(value: string): string {
	// Use JSON.stringify for safe escaping of quotes, backslashes, newlines, etc.
	return JSON.stringify(value);
}

function render(topics: Topic[]): string {
	const header = [
		"// AUTO-GENERATED by scripts/gen-help-topics.ts — do not edit manually.",
		"// Run `bun run gen:help` to regenerate after editing docs/help/topics/*.md.",
		"",
		"export interface HelpTopic {",
		"\treadonly name: string;",
		"\treadonly description: string;",
		"\treadonly content: string;",
		"}",
		"",
		"export const helpTopics: Readonly<Record<string, HelpTopic>> = Object.freeze({",
	];
	const body: string[] = [];
	for (const topic of topics) {
		body.push(`\t${JSON.stringify(topic.name)}: Object.freeze({`);
		body.push(`\t\tname: ${serializeString(topic.name)},`);
		body.push(`\t\tdescription: ${serializeString(topic.description)},`);
		body.push(`\t\tcontent: ${serializeString(topic.content)},`);
		body.push("\t}),");
	}
	const footer = ["});", ""];
	return [...header, ...body, ...footer].join("\n");
}

function formatWithBiome(file: string): void {
	// Run biome on just this file so the generated output matches the
	// project's formatting rules and `bun run fmt` stays idempotent.
	const result = spawnSync(
		"bunx",
		["biome", "format", "--write", relative(ROOT, file)],
		{
			cwd: ROOT,
			stdio: "inherit",
		},
	);
	if (result.status !== 0) {
		process.exit(result.status ?? 1);
	}
}

function main(): void {
	const topics = collectTopics();
	const output = render(topics);
	writeFileSync(OUT_FILE, output, "utf-8");
	formatWithBiome(OUT_FILE);
	console.log(
		`Generated ${OUT_FILE} (${topics.length} topic${topics.length === 1 ? "" : "s"})`,
	);
}

main();
