import { z } from "zod";
import type { CommandMeta } from "@/src/core/types";
import {
	DEFAULT_DISK_SIZE,
	DEFAULT_MEMORY,
	DEFAULT_VCPU,
} from "@/src/utils/constants";
import {
	cvmIdOption,
	interactiveOption,
	privateKeyOption,
	rpcUrlOption,
	transactionHashOption,
	uuidOption,
} from "@/src/core/common-flags";

export const deployCommandMeta: CommandMeta = {
	name: "deploy",
	category: "deploy",
	description: "Deploy new CVM or update existing one",
	stability: "stable",
	arguments: [],
	options: [
		cvmIdOption,
		uuidOption,
		interactiveOption,
		{
			name: "debug",
			description: "Enable debug logging",
			type: "boolean",
			target: "debug",
			group: "advanced",
		},
		{
			name: "name",
			shorthand: "n",
			description: "CVM name (defaults to directory name)",
			type: "string",
			target: "name",
			group: "basic",
		},
		{
			name: "compose",
			shorthand: "c",
			description: "Path to Docker Compose file (default: docker-compose.yml)",
			type: "string",
			target: "compose",
			group: "basic",
		},
		{
			name: "instance-type",
			shorthand: "t",
			description: "Instance type (e.g., tdx.small, auto-selected if omitted)",
			type: "string",
			target: "instanceType",
			group: "basic",
		},
		{
			name: "vcpu",
			description: "Use --instance-type instead",
			type: "string",
			target: "vcpu",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "memory",
			description: "Use --instance-type instead",
			type: "string",
			target: "memory",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "disk-size",
			description: `Disk size with unit (e.g., 50G, default: ${DEFAULT_DISK_SIZE}GB)`,
			type: "string",
			target: "diskSize",
			group: "advanced",
		},
		{
			name: "fs",
			description: "Filesystem type (ext4 or zfs, default: zfs)",
			type: "string",
			target: "fs",
			group: "advanced",
		},
		{
			name: "image",
			description: "OS image version (auto-selected if omitted)",
			type: "string",
			target: "image",
			group: "advanced",
		},
		{
			name: "region",
			shorthand: "r",
			description: "Preferred region (e.g., us-west, auto-selected if omitted)",
			type: "string",
			target: "region",
			group: "basic",
		},
		{
			name: "node-id",
			description: "Node ID (auto-selected if omitted)",
			type: "string",
			target: "nodeId",
			group: "advanced",
		},
		{
			name: "env",
			shorthand: "e",
			description:
				"Environment variable (KEY=VALUE) or env file path (repeatable)",
			type: "string[]",
			target: "env",
			group: "basic",
		},
		{
			name: "env-file",
			description: "Use -e instead",
			type: "string",
			target: "envFile",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "kms",
			description: "KMS type: phala (default), ethereum/eth, or base",
			type: "string",
			target: "kms",
			group: "basic",
		},
		{
			name: "kms-id",
			description: "Use --kms instead",
			type: "string",
			target: "kmsId",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "kms-contract",
			description: "KMS contract address",
			type: "string",
			target: "kmsContract",
			group: "advanced",
		},
		{
			name: "kms-contract-id",
			description: "KMS contract ID",
			type: "string",
			target: "kmsContractId",
			group: "advanced",
		},
		{
			name: "key-provider-mode",
			description: "Key provider mode: kms or local",
			type: "string",
			target: "keyProviderMode",
			group: "advanced",
		},
		{
			name: "experimental-key-provider-type",
			description:
				"Set key_provider in compose (kms, local, tpm). Backend resolves key_provider_id for kms; local/tpm require manual key_provider_id. Computes and displays mr_config_id after provision.",
			type: "string",
			target: "experimentalKeyProviderType",
			group: "advanced",
		},
		{
			name: "skip-gateway",
			description: "Skip gateway matching",
			type: "boolean",
			target: "skipGateway",
			group: "advanced",
		},
		{
			name: "custom-app-id",
			description: "Custom App ID (requires --nonce for PHALA KMS)",
			type: "string",
			target: "customAppId",
			group: "advanced",
		},
		{
			name: "nonce",
			description:
				"Nonce for deterministic app_id (requires --custom-app-id, PHALA KMS only)",
			type: "string",
			target: "nonce",
			group: "advanced",
		},
		{
			name: "pre-launch-script",
			description: "Path to pre-launch script",
			type: "string",
			target: "preLaunchScript",
			group: "advanced",
		},
		privateKeyOption,
		rpcUrlOption,
		{
			name: "wait",
			description: "Wait for deployment/update completion",
			type: "boolean",
			target: "wait",
			group: "basic",
		},
		{
			name: "ssh-pubkey",
			description: "SSH public key path (default: ~/.ssh/id_rsa.pub)",
			type: "string",
			target: "sshPubkey",
			group: "basic",
		},
		{
			name: "dev-os",
			description: "Use dev OS image (requires SSH key)",
			type: "boolean",
			target: "devOs",
			negatedName: "no-dev-os",
			group: "basic",
		},
		{
			name: "prepare-only",
			description:
				"Prepare the update and generate a commit token. Skips all on-chain operations. Intended for multisig workflows.",
			type: "boolean",
			target: "prepareOnly",
			group: "advanced",
		},
		{
			name: "commit",
			description:
				"Commit a previously prepared update using a commit token. Requires --token; --compose-hash and --transaction-hash are read from the token when omitted.",
			type: "boolean",
			target: "commit",
			group: "advanced",
		},
		{
			name: "token",
			description: "Commit token from a prepare-only update.",
			type: "string",
			target: "token",
			group: "advanced",
		},
		{
			name: "compose-hash",
			description:
				"Compose hash from a prepare-only update. Optional in --commit mode when the token can provide it.",
			type: "string",
			target: "composeHash",
			group: "advanced",
		},
		transactionHashOption,
		{
			name: "public-logs",
			description: "Make CVM logs publicly accessible (default: true)",
			type: "boolean",
			target: "publicLogs",
			negatedName: "no-public-logs",
		},
		{
			name: "public-sysinfo",
			description: "Make CVM system info publicly accessible (default: true)",
			type: "boolean",
			target: "publicSysinfo",
			negatedName: "no-public-sysinfo",
		},
		{
			name: "public-tcbinfo",
			description: "Make attestation data publicly accessible (default: true)",
			type: "boolean",
			target: "publicTcbinfo",
			negatedName: "no-public-tcbinfo",
		},
		{
			name: "secure-time",
			description: "Enable secure time (default: false)",
			type: "boolean",
			target: "secureTime",
			negatedName: "no-secure-time",
		},
		{
			name: "listed",
			description: "List CVM on the public Trust Center (default: false)",
			type: "boolean",
			target: "listed",
			negatedName: "no-listed",
		},
	],
	examples: [
		// --- New Deployment Examples ---
		{
			name: "Deploy new CVM",
			value: "phala deploy",
		},
		{
			name: "Deploy with environment variables",
			value: "phala deploy -e NODE_ENV=production -e DEBUG=true",
		},
		{
			name: "Deploy with env file",
			value: "phala deploy -e .env",
		},
		{
			name: "Deploy with specific instance type",
			value: "phala deploy --instance-type tdx.medium",
		},
		{
			name: "Deploy to specific region",
			value: "phala deploy --region us-west",
		},
		{
			name: "Deploy with Ethereum KMS",
			value: "phala deploy --kms ethereum --private-key <key> --rpc-url <url>",
		},
		// --- Update Existing CVM Examples ---
		{
			name: "Update existing CVM by ID",
			value: "phala deploy --cvm-id app_abc123",
		},
		{
			name: "Update CVM with new compose file and env",
			value:
				"phala deploy --cvm-id my-app --compose ./new-docker-compose.yml -e .env",
		},
		{
			name: "Update CVM and wait for completion",
			value: "phala deploy --cvm-id app_abc123 --wait",
		},
		{
			name: "Update CVM from phala.toml",
			value: "phala deploy",
		},
		// --- Privacy Settings Examples ---
		{
			name: "Deploy with logs and sysinfo disabled",
			value: "phala deploy --no-public-logs --no-public-sysinfo",
		},
		{
			name: "Deploy and list on Trust Center",
			value: "phala deploy --listed",
		},
		{
			name: "Update existing CVM to disable logs",
			value: "phala deploy --cvm-id app_123 --no-public-logs",
		},
		// --- Multisig / Prepare-Only Examples ---
		{
			name: "Prepare update for multisig approval",
			value:
				"phala deploy --cvm-id app_123 --prepare-only -c docker-compose.yml",
		},
		{
			name: "Commit a prepared update",
			value:
				"phala deploy --cvm-id app_123 --commit --token <token> --compose-hash 0x... --transaction-hash 0x...",
		},
	],
};

export const deployCommandSchema = z.object({
	compose: z.string().optional(),
	json: z.boolean().default(false),
	debug: z.boolean().default(false),
	apiToken: z.string().optional(),
	name: z.string().optional(),
	instanceType: z.string().optional(),
	vcpu: z.string().optional(),
	memory: z.string().optional(),
	diskSize: z.string().optional(),
	fs: z.enum(["ext4", "zfs"]).optional(),
	image: z.string().optional(),
	region: z.string().optional(),
	nodeId: z.string().optional(),
	env: z.array(z.string()).optional(),
	envFile: z.string().optional(),
	interactive: z.boolean().default(false),
	kms: z.enum(["phala", "ethereum", "eth", "base"]).default("phala"),
	kmsId: z.string().optional(),
	kmsContract: z.string().optional(),
	kmsContractId: z.string().optional(),
	keyProviderMode: z.enum(["kms", "local"]).optional(),
	experimentalKeyProviderType: z.enum(["kms", "local", "tpm"]).optional(),
	skipGateway: z.boolean().optional(),
	cvmId: z.string().optional(),
	customAppId: z.string().optional(),
	nonce: z.string().optional(),
	preLaunchScript: z.string().optional(),
	privateKey: z.string().optional(),
	rpcUrl: z.string().optional(),
	wait: z.boolean().default(false),
	sshPubkey: z.string().optional(),
	devOs: z.boolean().optional(),
	publicLogs: z.boolean().optional(),
	publicSysinfo: z.boolean().optional(),
	publicTcbinfo: z.boolean().optional(),
	secureTime: z.boolean().optional(),
	listed: z.boolean().optional(),
	prepareOnly: z.boolean().default(false),
	commit: z.boolean().default(false),
	token: z.string().optional(),
	composeHash: z.string().optional(),
	transactionHash: z.string().optional(),
});

export type DeployCommandInput = z.infer<typeof deployCommandSchema>;
