name: Validate Config

on:
  push:
    paths:
      - 'awesome-phala-cloud/templates/config.json'
      - 'awesome-phala-cloud/templates/config.schema.json'
      - 'awesome-phala-cloud/templates/validate.py'
      - 'awesome-phala-cloud/templates/icons/**'
  pull_request:
    paths:
      - 'awesome-phala-cloud/templates/config.json'
      - 'awesome-phala-cloud/templates/config.schema.json'
      - 'awesome-phala-cloud/templates/validate.py'
      - 'awesome-phala-cloud/templates/icons/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
        
    - name: Run validation
      run: |
        cd awesome-phala-cloud/templates
        python validate.py 